###
// Get auth Data
GET http://localhost:3000/user/auth
Content-Type: application/json

###
// Register
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "email": "email@email.com",
  "username": "username",
  "password": "password"
}

###
// Login
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

###
// Logout
DELETE http://localhost:3000/user/logout

###
// Delete user by id
DELETE  http://localhost:3000/user/1

###
// Patch user by password and new fields 
PATCH  http://localhost:3000/user
Content-Type: application/json

{
  "username": "usernameEdited2",
  "password": "password"
}